/// do not modify this file! ///
/*used uplugins start
used uplugins end*/

#ifdef __cplusplus
#include <ValueTypes/value.h>
using namespace FlexitekMath::ValueTypes;
extern "C" {
#else
#define fxValue void
#endif

fxValue __declspec(dllexport) afp_get_last_error();
fxValue __declspec(dllexport) afp_get_last_errorName();
fxValue __declspec(dllexport) afp_get_last_errorDescription();
fxValue __declspec(dllexport) afp_get_last_errorImage();
fxValue __declspec(dllexport) afp_clear_last_error();
fxValue __declspec(dllexport) afp_clear_last_errorName();
fxValue __declspec(dllexport) afp_clear_last_errorDescription();
fxValue __declspec(dllexport) afp_clear_last_errorImage();
fxValue __declspec(dllexport) afp_supported_backends();
fxValue __declspec(dllexport) afp_supported_backendsName();
fxValue __declspec(dllexport) afp_supported_backendsDescription();
fxValue __declspec(dllexport) afp_supported_backendsImage();
fxValue __declspec(dllexport) afp_set_backend(const fxValue& backend);
fxValue __declspec(dllexport) afp_set_backendName();
fxValue __declspec(dllexport) afp_set_backendDescription();
fxValue __declspec(dllexport) afp_set_backendImage();
fxValue __declspec(dllexport) afp_backend();
fxValue __declspec(dllexport) afp_backendName();
fxValue __declspec(dllexport) afp_backendDescription();
fxValue __declspec(dllexport) afp_backendImage();
fxValue __declspec(dllexport) afp_set_device(const fxValue& device);
fxValue __declspec(dllexport) afp_set_deviceName();
fxValue __declspec(dllexport) afp_set_deviceDescription();
fxValue __declspec(dllexport) afp_set_deviceImage();
fxValue __declspec(dllexport) afp_get_device_count();
fxValue __declspec(dllexport) afp_get_device_countName();
fxValue __declspec(dllexport) afp_get_device_countDescription();
fxValue __declspec(dllexport) afp_get_device_countImage();
fxValue __declspec(dllexport) afp_device_info();
fxValue __declspec(dllexport) afp_device_infoName();
fxValue __declspec(dllexport) afp_device_infoDescription();
fxValue __declspec(dllexport) afp_device_infoImage();
fxValue __declspec(dllexport) afp_get_device();
fxValue __declspec(dllexport) afp_get_deviceName();
fxValue __declspec(dllexport) afp_get_deviceDescription();
fxValue __declspec(dllexport) afp_get_deviceImage();

//**********Random number generator**********
fxValue __declspec(dllexport) afp_randn(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_randnName();
fxValue __declspec(dllexport) afp_randnDescription();
fxValue __declspec(dllexport) afp_randnImage();
fxValue __declspec(dllexport) afp_randu(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_randuName();
fxValue __declspec(dllexport) afp_randuDescription();
fxValue __declspec(dllexport) afp_randuImage();
fxValue __declspec(dllexport) afp_constant(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_constantName();
fxValue __declspec(dllexport) afp_constantDescription();
fxValue __declspec(dllexport) afp_constantImage();
fxValue __declspec(dllexport) afp_diag_create(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_diag_createName();
fxValue __declspec(dllexport) afp_diag_createDescription();
fxValue __declspec(dllexport) afp_diag_createImage();
fxValue __declspec(dllexport) afp_diag_extract(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_diag_extractName();
fxValue __declspec(dllexport) afp_diag_extractDescription();
fxValue __declspec(dllexport) afp_diag_extractImage();
fxValue __declspec(dllexport) afp_identity(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_identityName();
fxValue __declspec(dllexport) afp_identityDescription();
fxValue __declspec(dllexport) afp_identityImage();
fxValue __declspec(dllexport) afp_lower(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_lowerName();
fxValue __declspec(dllexport) afp_lowerDescription();
fxValue __declspec(dllexport) afp_lowerImage();
fxValue __declspec(dllexport) afp_range(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_rangeName();
fxValue __declspec(dllexport) afp_rangeDescription();
fxValue __declspec(dllexport) afp_rangeImage();
fxValue __declspec(dllexport) afp_upper(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_upperName();
fxValue __declspec(dllexport) afp_upperDescription();
fxValue __declspec(dllexport) afp_upperImage();

//**********Move and Reorder Array**********
fxValue __declspec(dllexport) afp_flat(const fxValue& value1);
fxValue __declspec(dllexport) afp_flatName();
fxValue __declspec(dllexport) afp_flatDescription();
fxValue __declspec(dllexport) afp_flatImage();
fxValue __declspec(dllexport) afp_flip(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_flipName();
fxValue __declspec(dllexport) afp_flipDescription();
fxValue __declspec(dllexport) afp_flipImage();
fxValue __declspec(dllexport) afp_join(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_joinName();
fxValue __declspec(dllexport) afp_joinDescription();
fxValue __declspec(dllexport) afp_joinImage();
fxValue __declspec(dllexport) afp_moddims(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_moddimsName();
fxValue __declspec(dllexport) afp_moddimsDescription();
fxValue __declspec(dllexport) afp_moddimsImage();
//fxValue __declspec(dllexport) afp_replace(const fxValue& value1, const fxValue& value2, const fxValue& value3);
//fxValue __declspec(dllexport) afp_select(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_shift(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_shiftName();
fxValue __declspec(dllexport) afp_shiftDescription();
fxValue __declspec(dllexport) afp_shiftImage();
fxValue __declspec(dllexport) afp_tile(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_tileName();
fxValue __declspec(dllexport) afp_tileDescription();
fxValue __declspec(dllexport) afp_tileImage();

//**********Linear algebra**********
fxValue __declspec(dllexport) afp_dot(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_dotName();
fxValue __declspec(dllexport) afp_dotDescription();
fxValue __declspec(dllexport) afp_dotImage();
fxValue __declspec(dllexport) afp_matmul(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_matmulName();
fxValue __declspec(dllexport) afp_matmulDescription();
fxValue __declspec(dllexport) afp_matmulImage();
fxValue __declspec(dllexport) afp_transpose(const fxValue& value, const fxValue& value1);
fxValue __declspec(dllexport) afp_transposeName();
fxValue __declspec(dllexport) afp_transposeDescription();
fxValue __declspec(dllexport) afp_transposeImage();
//fxValue __declspec(dllexport) afp_solve(const fxValue& value, const fxValue& value1);
//fxValue __declspec(dllexport) afp_solveName();
//fxValue __declspec(dllexport) afp_solveDescription();
//fxValue __declspec(dllexport) afp_solveImage();
//fxValue __declspec(dllexport) afp_solve_lu(const fxValue& value, const fxValue& value1, const fxValue& value2);
//fxValue __declspec(dllexport) afp_solve_luName();
//fxValue __declspec(dllexport) afp_solve_luDescription();
//fxValue __declspec(dllexport) afp_solve_luImage();
fxValue __declspec(dllexport) afp_cholesky(const fxValue& value,const fxValue& value1);
fxValue __declspec(dllexport) afp_choleskyName();
fxValue __declspec(dllexport) afp_choleskyDescription();
fxValue __declspec(dllexport) afp_choleskyImage();
fxValue __declspec(dllexport) afp_lu(const fxValue& value);
fxValue __declspec(dllexport) afp_luName();
fxValue __declspec(dllexport) afp_luDescription();
fxValue __declspec(dllexport) afp_luImage();
fxValue __declspec(dllexport) afp_lu_low(const fxValue& value);
fxValue __declspec(dllexport) afp_lu_lowName();
fxValue __declspec(dllexport) afp_lu_lowDescription();
fxValue __declspec(dllexport) afp_lu_lowImage();
fxValue __declspec(dllexport) afp_lu_upp(const fxValue& value);
fxValue __declspec(dllexport) afp_lu_uppName();
fxValue __declspec(dllexport) afp_lu_uppDescription();
fxValue __declspec(dllexport) afp_lu_uppImage();
fxValue __declspec(dllexport) afp_lu_piv(const fxValue& value);
fxValue __declspec(dllexport) afp_lu_pivName();
fxValue __declspec(dllexport) afp_lu_pivDescription();
fxValue __declspec(dllexport) afp_lu_pivImage();
fxValue __declspec(dllexport) afp_qr(const fxValue& value);
fxValue __declspec(dllexport) afp_qrName();
fxValue __declspec(dllexport) afp_qrDescription();
fxValue __declspec(dllexport) afp_qrImage();
fxValue __declspec(dllexport) afp_qr_q(const fxValue& value);
fxValue __declspec(dllexport) afp_qr_qName();
fxValue __declspec(dllexport) afp_qr_qDescription();
fxValue __declspec(dllexport) afp_qr_qImage();
fxValue __declspec(dllexport) afp_qr_r(const fxValue& value);
fxValue __declspec(dllexport) afp_qr_rName();
fxValue __declspec(dllexport) afp_qr_rDescription();
fxValue __declspec(dllexport) afp_qr_rImage();
fxValue __declspec(dllexport) afp_svd(const fxValue& value);
fxValue __declspec(dllexport) afp_svdName();
fxValue __declspec(dllexport) afp_svdDescription();
fxValue __declspec(dllexport) afp_svdImage();
fxValue __declspec(dllexport) afp_svd_u(const fxValue& value);
fxValue __declspec(dllexport) afp_svd_uName();
fxValue __declspec(dllexport) afp_svd_uDescription();
fxValue __declspec(dllexport) afp_svd_uImage();
fxValue __declspec(dllexport) afp_svd_s(const fxValue& value);
fxValue __declspec(dllexport) afp_svd_sName();
fxValue __declspec(dllexport) afp_svd_sDescription();
fxValue __declspec(dllexport) afp_svd_sImage();
fxValue __declspec(dllexport) afp_svd_v(const fxValue& value);
fxValue __declspec(dllexport) afp_svd_vName();
fxValue __declspec(dllexport) afp_svd_vDescription();
fxValue __declspec(dllexport) afp_svd_vImage();
fxValue __declspec(dllexport) afp_det(const fxValue& value);
fxValue __declspec(dllexport) afp_detName();
fxValue __declspec(dllexport) afp_detDescription();
fxValue __declspec(dllexport) afp_detImage();
fxValue __declspec(dllexport) afp_inverse(const fxValue& value);
fxValue __declspec(dllexport) afp_inverseName();
fxValue __declspec(dllexport) afp_inverseDescription();
fxValue __declspec(dllexport) afp_inverseImage();
fxValue __declspec(dllexport) afp_norm(const fxValue& value, const fxValue& value1);
fxValue __declspec(dllexport) afp_normName();
fxValue __declspec(dllexport) afp_normDescription();
fxValue __declspec(dllexport) afp_normImage();
fxValue __declspec(dllexport) afp_pinverse(const fxValue& value);
fxValue __declspec(dllexport) afp_pinverseName();
fxValue __declspec(dllexport) afp_pinverseDescription();
fxValue __declspec(dllexport) afp_pinverseImage();
fxValue __declspec(dllexport) afp_rank(const fxValue& value);
fxValue __declspec(dllexport) afp_rankName();
fxValue __declspec(dllexport) afp_rankDescription();
fxValue __declspec(dllexport) afp_rankImage();

//**********Machine Learning**********
fxValue __declspec(dllexport) afp_convolve2_gradient_nn(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4, const fxValue& value5, const fxValue& value6, const fxValue& value7, const fxValue& value8);
fxValue __declspec(dllexport) afp_convolve2_gradient_nnName();
fxValue __declspec(dllexport) afp_convolve2_gradient_nnDescription();
fxValue __declspec(dllexport) afp_convolve2_gradient_nnImage();

//**********Complex functions**********
fxValue __declspec(dllexport) afp_conjg(const fxValue& value1);
fxValue __declspec(dllexport) afp_conjgName();
fxValue __declspec(dllexport) afp_conjgDescription();
fxValue __declspec(dllexport) afp_conjgImage();
fxValue __declspec(dllexport) afp_imag(const fxValue& value1);
fxValue __declspec(dllexport) afp_imagName();
fxValue __declspec(dllexport) afp_imagDescription();
fxValue __declspec(dllexport) afp_imagImage();
fxValue __declspec(dllexport) afp_real(const fxValue& value1);
fxValue __declspec(dllexport) afp_realName();
fxValue __declspec(dllexport) afp_realDescription();
fxValue __declspec(dllexport) afp_realImage();

//**********Exponential and logarithmic functions**********
fxValue __declspec(dllexport) afp_cbrt(const fxValue& value1);
fxValue __declspec(dllexport) afp_cbrtName();
fxValue __declspec(dllexport) afp_cbrtDescription();
fxValue __declspec(dllexport) afp_cbrtImage();
fxValue __declspec(dllexport) afp_erf(const fxValue& value1);
fxValue __declspec(dllexport) afp_erfName();
fxValue __declspec(dllexport) afp_erfDescription();
fxValue __declspec(dllexport) afp_erfImage();
fxValue __declspec(dllexport) afp_erfc(const fxValue& value1);
fxValue __declspec(dllexport) afp_erfcName();
fxValue __declspec(dllexport) afp_erfcDescription();
fxValue __declspec(dllexport) afp_erfcImage();
fxValue __declspec(dllexport) afp_exp(const fxValue& value1);
fxValue __declspec(dllexport) afp_expName();
fxValue __declspec(dllexport) afp_expDescription();
fxValue __declspec(dllexport) afp_expImage();
fxValue __declspec(dllexport) afp_expm1(const fxValue& value1);
fxValue __declspec(dllexport) afp_expm1Name();
fxValue __declspec(dllexport) afp_expm1Description();
fxValue __declspec(dllexport) afp_expm1Image();
fxValue __declspec(dllexport) afp_factorial(const fxValue& value1);
fxValue __declspec(dllexport) afp_factorialName();
fxValue __declspec(dllexport) afp_factorialDescription();
fxValue __declspec(dllexport) afp_factorialImage();
fxValue __declspec(dllexport) afp_lgamma(const fxValue& value1);
fxValue __declspec(dllexport) afp_lgammaName();
fxValue __declspec(dllexport) afp_lgammaDescription();
fxValue __declspec(dllexport) afp_lgammaImage();
fxValue __declspec(dllexport) afp_log(const fxValue& value1);
fxValue __declspec(dllexport) afp_logName();
fxValue __declspec(dllexport) afp_logDescription();
fxValue __declspec(dllexport) afp_logImage();
fxValue __declspec(dllexport) afp_log10(const fxValue& value1);
fxValue __declspec(dllexport) afp_log10Name();
fxValue __declspec(dllexport) afp_log10Description();
fxValue __declspec(dllexport) afp_log10Image();
fxValue __declspec(dllexport) afp_log1p(const fxValue& value1);
fxValue __declspec(dllexport) afp_log1pName();
fxValue __declspec(dllexport) afp_log1pDescription();
fxValue __declspec(dllexport) afp_log1pImage();
fxValue __declspec(dllexport) afp_pow(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_powName();
fxValue __declspec(dllexport) afp_powDescription();
fxValue __declspec(dllexport) afp_powImage();
fxValue __declspec(dllexport) afp_root(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_rootName();
fxValue __declspec(dllexport) afp_rootDescription();
fxValue __declspec(dllexport) afp_rootImage();
fxValue __declspec(dllexport) afp_rsqrt(const fxValue& value1);
fxValue __declspec(dllexport) afp_rsqrtName();
fxValue __declspec(dllexport) afp_rsqrtDescription();
fxValue __declspec(dllexport) afp_rsqrtImage();
fxValue __declspec(dllexport) afp_sqrt(const fxValue& value1);
fxValue __declspec(dllexport) afp_sqrtName();
fxValue __declspec(dllexport) afp_sqrtDescription();
fxValue __declspec(dllexport) afp_sqrtImage();
fxValue __declspec(dllexport) afp_tgamma(const fxValue& value1);
fxValue __declspec(dllexport) afp_tgammaName();
fxValue __declspec(dllexport) afp_tgammaDescription();
fxValue __declspec(dllexport) afp_tgammaImage();

//**********Hyperbolic functions**********
fxValue __declspec(dllexport) afp_acosh(const fxValue& value1);
fxValue __declspec(dllexport) afp_acoshName();
fxValue __declspec(dllexport) afp_acoshDescription();
fxValue __declspec(dllexport) afp_acoshImage();
fxValue __declspec(dllexport) afp_asinh(const fxValue& value1);
fxValue __declspec(dllexport) afp_asinhName();
fxValue __declspec(dllexport) afp_asinhDescription();
fxValue __declspec(dllexport) afp_asinhImage();
fxValue __declspec(dllexport) afp_atanh(const fxValue& value1);
fxValue __declspec(dllexport) afp_atanhName();
fxValue __declspec(dllexport) afp_atanhDescription();
fxValue __declspec(dllexport) afp_atanhImage();
fxValue __declspec(dllexport) afp_cosh(const fxValue& value1);
fxValue __declspec(dllexport) afp_coshName();
fxValue __declspec(dllexport) afp_coshDescription();
fxValue __declspec(dllexport) afp_coshImage();
fxValue __declspec(dllexport) afp_sinh(const fxValue& value1);
fxValue __declspec(dllexport) afp_sinhName();
fxValue __declspec(dllexport) afp_sinhDescription();
fxValue __declspec(dllexport) afp_sinhImage();
fxValue __declspec(dllexport) afp_tanh(const fxValue& value1);
fxValue __declspec(dllexport) afp_tanhName();
fxValue __declspec(dllexport) afp_tanhDescription();
fxValue __declspec(dllexport) afp_tanhImage();

//**********Numeric functions**********
fxValue __declspec(dllexport) afp_abs(const fxValue& value1);
fxValue __declspec(dllexport) afp_absName();
fxValue __declspec(dllexport) afp_absDescription();
fxValue __declspec(dllexport) afp_absImage();
fxValue __declspec(dllexport) afp_arg(const fxValue& value1);
fxValue __declspec(dllexport) afp_argName();
fxValue __declspec(dllexport) afp_argDescription();
fxValue __declspec(dllexport) afp_argImage();
fxValue __declspec(dllexport) afp_ceil(const fxValue& value1);
fxValue __declspec(dllexport) afp_ceilName();
fxValue __declspec(dllexport) afp_ceilDescription();
fxValue __declspec(dllexport) afp_ceilImage();
fxValue __declspec(dllexport) afp_floor(const fxValue& value1);
fxValue __declspec(dllexport) afp_floorName();
fxValue __declspec(dllexport) afp_floorDescription();
fxValue __declspec(dllexport) afp_floorImage();
fxValue __declspec(dllexport) afp_hypot(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_hypotName();
fxValue __declspec(dllexport) afp_hypotDescription();
fxValue __declspec(dllexport) afp_hypotImage();
fxValue __declspec(dllexport) afp_maxof(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_maxofName();
fxValue __declspec(dllexport) afp_maxofDescription();
fxValue __declspec(dllexport) afp_maxofImage();
fxValue __declspec(dllexport) afp_minof(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_minofName();
fxValue __declspec(dllexport) afp_minofDescription();
fxValue __declspec(dllexport) afp_minofImage();
fxValue __declspec(dllexport) afp_mod(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_modName();
fxValue __declspec(dllexport) afp_modDescription();
fxValue __declspec(dllexport) afp_modImage();
fxValue __declspec(dllexport) afp_rem(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_remName();
fxValue __declspec(dllexport) afp_remDescription();
fxValue __declspec(dllexport) afp_remImage();
fxValue __declspec(dllexport) afp_round(const fxValue& value1);
fxValue __declspec(dllexport) afp_roundName();
fxValue __declspec(dllexport) afp_roundDescription();
fxValue __declspec(dllexport) afp_roundImage();
fxValue __declspec(dllexport) afp_sign(const fxValue& value1);
fxValue __declspec(dllexport) afp_signName();
fxValue __declspec(dllexport) afp_signDescription();
fxValue __declspec(dllexport) afp_signImage();
fxValue __declspec(dllexport) afp_trunc(const fxValue& value1);
fxValue __declspec(dllexport) afp_truncName();
fxValue __declspec(dllexport) afp_truncDescription();
fxValue __declspec(dllexport) afp_truncImage();

//**********Trigonometric functions**********
fxValue __declspec(dllexport) afp_acos(const fxValue& value1);
fxValue __declspec(dllexport) afp_acosName();
fxValue __declspec(dllexport) afp_acosDescription();
fxValue __declspec(dllexport) afp_acosImage();
fxValue __declspec(dllexport) afp_asin(const fxValue& value1);
fxValue __declspec(dllexport) afp_asinName();
fxValue __declspec(dllexport) afp_asinDescription();
fxValue __declspec(dllexport) afp_asinImage();
fxValue __declspec(dllexport) afp_atan(const fxValue& value1);
fxValue __declspec(dllexport) afp_atanName();
fxValue __declspec(dllexport) afp_atanDescription();
fxValue __declspec(dllexport) afp_atanImage();
fxValue __declspec(dllexport) afp_atan2(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_atan2Name();
fxValue __declspec(dllexport) afp_atan2Description();
fxValue __declspec(dllexport) afp_atan2Image();
fxValue __declspec(dllexport) afp_cos(const fxValue& value1);
fxValue __declspec(dllexport) afp_cosName();
fxValue __declspec(dllexport) afp_cosDescription();
fxValue __declspec(dllexport) afp_cosImage();
fxValue __declspec(dllexport) afp_sin(const fxValue& value1);
fxValue __declspec(dllexport) afp_sinName();
fxValue __declspec(dllexport) afp_sinDescription();
fxValue __declspec(dllexport) afp_sinImage();
fxValue __declspec(dllexport) afp_tan(const fxValue& value1);
fxValue __declspec(dllexport) afp_tanName();
fxValue __declspec(dllexport) afp_tanDescription();
fxValue __declspec(dllexport) afp_tanImage();

//**********Signal Processing**********
fxValue __declspec(dllexport) afp_convolve2_sep(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
fxValue __declspec(dllexport) afp_convolve2_sepName();
fxValue __declspec(dllexport) afp_convolve2_sepDescription();
fxValue __declspec(dllexport) afp_convolve2_sepImage();
fxValue __declspec(dllexport) afp_convolve1(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
fxValue __declspec(dllexport) afp_convolve1Name();
fxValue __declspec(dllexport) afp_convolve1Description();
fxValue __declspec(dllexport) afp_convolve1Image();
fxValue __declspec(dllexport) afp_fft_convolve1(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_fft_convolve1Name();
fxValue __declspec(dllexport) afp_fft_convolve1Description();
fxValue __declspec(dllexport) afp_fft_convolve1Image();
fxValue __declspec(dllexport) afp_convolve2(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
fxValue __declspec(dllexport) afp_convolve2Name();
fxValue __declspec(dllexport) afp_convolve2Description();
fxValue __declspec(dllexport) afp_convolve2Image();
fxValue __declspec(dllexport) afp_convolve2_nn(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4, const fxValue& value5);
fxValue __declspec(dllexport) afp_convolve2_nnName();
fxValue __declspec(dllexport) afp_convolve2_nnDescription();
fxValue __declspec(dllexport) afp_convolve2_nnImage();
fxValue __declspec(dllexport) afp_fft_convolve2(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_fft_convolve2Name();
fxValue __declspec(dllexport) afp_fft_convolve2Description();
fxValue __declspec(dllexport) afp_fft_convolve2Image();
fxValue __declspec(dllexport) afp_fft(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_fftName();
fxValue __declspec(dllexport) afp_fftDescription();
fxValue __declspec(dllexport) afp_fftImage();
fxValue __declspec(dllexport) afp_fft2(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
fxValue __declspec(dllexport) afp_fft2Name();
fxValue __declspec(dllexport) afp_fft2Description();
fxValue __declspec(dllexport) afp_fft2Image();
fxValue __declspec(dllexport) afp_fft_c2r(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_fft_c2rName();
fxValue __declspec(dllexport) afp_fft_c2rDescription();
fxValue __declspec(dllexport) afp_fft_c2rImage();
fxValue __declspec(dllexport) afp_fft2_c2r(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_fft2_c2rName();
fxValue __declspec(dllexport) afp_fft2_c2rDescription();
fxValue __declspec(dllexport) afp_fft2_c2rImage();
fxValue __declspec(dllexport) afp_fft_r2c(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_fft_r2cName();
fxValue __declspec(dllexport) afp_fft_r2cDescription();
fxValue __declspec(dllexport) afp_fft_r2cImage();
fxValue __declspec(dllexport) afp_fft2_r2c(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
fxValue __declspec(dllexport) afp_fft2_r2cName();
fxValue __declspec(dllexport) afp_fft2_r2cDescription();
fxValue __declspec(dllexport) afp_fft2_r2cImage();
fxValue __declspec(dllexport) afp_ifft(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_ifftName();
fxValue __declspec(dllexport) afp_ifftDescription();
fxValue __declspec(dllexport) afp_ifftImage();
fxValue __declspec(dllexport) afp_ifft2(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
fxValue __declspec(dllexport) afp_ifft2Name();
fxValue __declspec(dllexport) afp_ifft2Description();
fxValue __declspec(dllexport) afp_ifft2Image();
fxValue __declspec(dllexport) afp_fir(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_firName();
fxValue __declspec(dllexport) afp_firDescription();
fxValue __declspec(dllexport) afp_firImage();
fxValue __declspec(dllexport) afp_iir(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_iirName();
fxValue __declspec(dllexport) afp_iirDescription();
fxValue __declspec(dllexport) afp_iirImage();
//fxValue __declspec(dllexport) afp_approx1(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
//fxValue __declspec(dllexport) afp_approx1Name();
//fxValue __declspec(dllexport) afp_approx1Description();
//fxValue __declspec(dllexport) afp_approx1Image();
//fxValue __declspec(dllexport) afp_approx2(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4, const fxValue& value5);
//fxValue __declspec(dllexport) afp_approx2Name();
//fxValue __declspec(dllexport) afp_approx2Description();
//fxValue __declspec(dllexport) afp_approx2Image();

//**********Statistics**********
fxValue __declspec(dllexport) afp_corrcoef(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_corrcoefName();
fxValue __declspec(dllexport) afp_corrcoefDescription();
fxValue __declspec(dllexport) afp_corrcoefImage();
fxValue __declspec(dllexport) afp_cov(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_covName();
fxValue __declspec(dllexport) afp_covDescription();
fxValue __declspec(dllexport) afp_covImage();
fxValue __declspec(dllexport) afp_mean(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_meanName();
fxValue __declspec(dllexport) afp_meanDescription();
fxValue __declspec(dllexport) afp_meanImage();
fxValue __declspec(dllexport) afp_mean_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_mean_allName();
fxValue __declspec(dllexport) afp_mean_allDescription();
fxValue __declspec(dllexport) afp_mean_allImage();
fxValue __declspec(dllexport) afp_mean_all_weighted(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_mean_all_weightedName();
fxValue __declspec(dllexport) afp_mean_all_weightedDescription();
fxValue __declspec(dllexport) afp_mean_all_weightedImage();
fxValue __declspec(dllexport) afp_mean_weighted(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_mean_weightedName();
fxValue __declspec(dllexport) afp_mean_weightedDescription();
fxValue __declspec(dllexport) afp_mean_weightedImage();
fxValue __declspec(dllexport) afp_median(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_medianName();
fxValue __declspec(dllexport) afp_medianDescription();
fxValue __declspec(dllexport) afp_medianImage();
fxValue __declspec(dllexport) afp_median_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_median_allName();
fxValue __declspec(dllexport) afp_median_allDescription();
fxValue __declspec(dllexport) afp_median_allImage();
fxValue __declspec(dllexport) afp_stdev(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_stdevName();
fxValue __declspec(dllexport) afp_stdevDescription();
fxValue __declspec(dllexport) afp_stdevImage();
fxValue __declspec(dllexport) afp_stdev_all(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_stdev_allName();
fxValue __declspec(dllexport) afp_stdev_allDescription();
fxValue __declspec(dllexport) afp_stdev_allImage();
fxValue __declspec(dllexport) afp_topk(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_topkName();
fxValue __declspec(dllexport) afp_topkDescription();
fxValue __declspec(dllexport) afp_topkImage();
fxValue __declspec(dllexport) afp_var(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_varName();
fxValue __declspec(dllexport) afp_varDescription();
fxValue __declspec(dllexport) afp_varImage();
fxValue __declspec(dllexport) afp_var_all(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_var_allName();
fxValue __declspec(dllexport) afp_var_allDescription();
fxValue __declspec(dllexport) afp_var_allImage();
fxValue __declspec(dllexport) afp_var_weighted(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_var_weightedName();
fxValue __declspec(dllexport) afp_var_weightedDescription();
fxValue __declspec(dllexport) afp_var_weightedImage();
fxValue __declspec(dllexport) afp_var_all_weighted(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_var_all_weightedName();
fxValue __declspec(dllexport) afp_var_all_weightedDescription();
fxValue __declspec(dllexport) afp_var_all_weightedImage();

//**********Vector algorithms**********
fxValue __declspec(dllexport) afp_accum(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_accumName();
fxValue __declspec(dllexport) afp_accumDescription();
fxValue __declspec(dllexport) afp_accumImage();
fxValue __declspec(dllexport) afp_scan(const fxValue& value1, const fxValue& value2, const fxValue& value3, const fxValue& value4);
fxValue __declspec(dllexport) afp_scanName();
fxValue __declspec(dllexport) afp_scanDescription();
fxValue __declspec(dllexport) afp_scanImage();
fxValue __declspec(dllexport) afp_where(const fxValue& value1);
fxValue __declspec(dllexport) afp_whereName();
fxValue __declspec(dllexport) afp_whereDescription();
fxValue __declspec(dllexport) afp_whereImage();
fxValue __declspec(dllexport) afp_diff1(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_diff1Name();
fxValue __declspec(dllexport) afp_diff1Description();
fxValue __declspec(dllexport) afp_diff1Image();
fxValue __declspec(dllexport) afp_diff2(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_diff2Name();
fxValue __declspec(dllexport) afp_diff2Description();
fxValue __declspec(dllexport) afp_diff2Image();
fxValue __declspec(dllexport) afp_gradient(const fxValue& value1);
fxValue __declspec(dllexport) afp_gradientName();
fxValue __declspec(dllexport) afp_gradientDescription();
fxValue __declspec(dllexport) afp_gradientImage();
//fxValue __declspec(dllexport) afp_all_true(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_count(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_countName();
fxValue __declspec(dllexport) afp_countDescription();
fxValue __declspec(dllexport) afp_countImage();
fxValue __declspec(dllexport) afp_count_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_count_allName();
fxValue __declspec(dllexport) afp_count_allDescription();
fxValue __declspec(dllexport) afp_count_allImage();
fxValue __declspec(dllexport) afp_imax(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_imaxName();
fxValue __declspec(dllexport) afp_imaxDescription();
fxValue __declspec(dllexport) afp_imaxImage();
fxValue __declspec(dllexport) afp_imax_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_imax_allName();
fxValue __declspec(dllexport) afp_imax_allDescription();
fxValue __declspec(dllexport) afp_imax_allImage();
fxValue __declspec(dllexport) afp_max(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_maxName();
fxValue __declspec(dllexport) afp_maxDescription();
fxValue __declspec(dllexport) afp_maxImage();
fxValue __declspec(dllexport) afp_max_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_max_allName();
fxValue __declspec(dllexport) afp_max_allDescription();
fxValue __declspec(dllexport) afp_max_allImage();
fxValue __declspec(dllexport) afp_imin(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_iminName();
fxValue __declspec(dllexport) afp_iminDescription();
fxValue __declspec(dllexport) afp_iminImage();
fxValue __declspec(dllexport) afp_imin_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_imin_allName();
fxValue __declspec(dllexport) afp_imin_allDescription();
fxValue __declspec(dllexport) afp_imin_allImage();
fxValue __declspec(dllexport) afp_min(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_minName();
fxValue __declspec(dllexport) afp_minDescription();
fxValue __declspec(dllexport) afp_minImage();
fxValue __declspec(dllexport) afp_min_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_min_allName();
fxValue __declspec(dllexport) afp_min_allDescription();
fxValue __declspec(dllexport) afp_min_allImage();
fxValue __declspec(dllexport) afp_product(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_productName();
fxValue __declspec(dllexport) afp_productDescription();
fxValue __declspec(dllexport) afp_productImage();
fxValue __declspec(dllexport) afp_product_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_product_allName();
fxValue __declspec(dllexport) afp_product_allDescription();
fxValue __declspec(dllexport) afp_product_allImage();
fxValue __declspec(dllexport) afp_sum(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_sumName();
fxValue __declspec(dllexport) afp_sumDescription();
fxValue __declspec(dllexport) afp_sumImage();
fxValue __declspec(dllexport) afp_sum_all(const fxValue& value1);
fxValue __declspec(dllexport) afp_sum_allName();
fxValue __declspec(dllexport) afp_sum_allDescription();
fxValue __declspec(dllexport) afp_sum_allImage();
fxValue __declspec(dllexport) afp_set_intersect(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_set_intersectName();
fxValue __declspec(dllexport) afp_set_intersectDescription();
fxValue __declspec(dllexport) afp_set_intersectImage();
fxValue __declspec(dllexport) afp_set_union(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_set_unionName();
fxValue __declspec(dllexport) afp_set_unionDescription();
fxValue __declspec(dllexport) afp_set_unionImage();
fxValue __declspec(dllexport) afp_set_unique(const fxValue& value1, const fxValue& value2);
fxValue __declspec(dllexport) afp_set_uniqueName();
fxValue __declspec(dllexport) afp_set_uniqueDescription();
fxValue __declspec(dllexport) afp_set_uniqueImage();
fxValue __declspec(dllexport) afp_sort(const fxValue& value1, const fxValue& value2, const fxValue& value3);
fxValue __declspec(dllexport) afp_sortName();
fxValue __declspec(dllexport) afp_sortDescription();
fxValue __declspec(dllexport) afp_sortImage();

#ifdef __cplusplus
}
#endif

